[ RowDataPacket {
    item_id: 1,
    product_name: 'God of War',
    department_name: 'Video Games',
    price: 29.95,
    stock_quantity: 40 },
  RowDataPacket {
    item_id: 2,
    product_name: 'Uncharted',
    department_name: 'Video Games',
    price: 29.95,
    stock_quantity: 30 },
  RowDataPacket {
    item_id: 3,
    product_name: 'Dish Soap',
    department_name: 'Home Supplies',
    price: 2.95,
    stock_quantity: 100 },
  RowDataPacket {
    item_id: 4,
    product_name: 'Kitchen Paper Towels',
    department_name: 'Home Supplies',
    price: 10.95,
    stock_quantity: 120 },
  RowDataPacket {
    item_id: 5,
    product_name: 'Monopoly',
    department_name: 'Board Games',
    price: 19.95,
    stock_quantity: 35 },
  RowDataPacket {
    item_id: 6,
    product_name: 'Chess',
    department_name: 'Board Games',
    price: 14.95,
    stock_quantity: 40 },
  RowDataPacket {
    item_id: 7,
    product_name: 'Sequence',
    department_name: 'Board Games',
    price: 9.95,
    stock_quantity: 40 },
  RowDataPacket {
    item_id: 8,
    product_name: 'Titanic',
    department_name: 'Films',
    price: 15,
    stock_quantity: 55 },
  RowDataPacket {
    item_id: 9,
    product_name: 'Despicable Me',
    department_name: 'Films',
    price: 14.99,
    stock_quantity: 55 },
  RowDataPacket {
    item_id: 10,
    product_name: 'Ray Ban Sunglasses',
    department_name: 'Apparel',
    price: 102.95,
    stock_quantity: 125 },
  RowDataPacket {
    item_id: 11,
    product_name: 'Worn Denim Jeans',
    department_name: 'Apparel',
    price: 55.25,
    stock_quantity: 125 } ]